/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	public static void main(String args[]) {
		Library lib = new Library();
		if (lib.someLibraryMethod())
			System.out.println("test");
			System.out.println("!!!REDSOX EDIT!!!");
	}
    public boolean someLibraryMethod() {
        return true;
    }
}
